apiVersion: 1

contactPoints:
  - orgId: 1
    name: incident-responder
    receivers:
      - uid: incident-responder-webhook
        type: webhook
        disableResolveMessage: true
        settings:
          url: http://incident-response:8001/alerts
          httpMethod: POST
          maxAlerts: 0
